import { ProductModel } from "../models/product.model.ts";
import { v4 as uuidv4 } from "uuid";
import { initMongoDB } from "~/environments/environment.ts";

async function seedProducts() {
  await initMongoDB();
  await ProductModel.deleteMany({}); // Clear existing products

  const products = [
    {
      productId: `prod-${uuidv4().slice(0, 16)}`,
      name: "Traditional Mango Pickle",
      slug: "traditional-mango-pickle",
      description:
        "Authentic Hyderabadi style mango pickle with aromatic spices",
      longDescription: "Made with handpicked mangoes and traditional spices",
      category: "pickle",
      type: "veg",
      ingredients: ["mango", "mustard oil", "spices", "salt"],
      nutritionalInfo: {
        servingSize: "15g",
        calories: 30,
        fat: "2g",
        sodium: "300mg",
        carbs: "3g",
        fiber: "0.5g",
        protein: "0.2g",
        sugar: "1g",
      },
      price: 349,
      discount: 14, // (349 - 299) / 349 * 100 ≈ 14%
      stock: 100,
      inStock: true,
      spiceLevel: 3,
      isVeg: true,
      imageUrl: "/assets/thop2.png",
      images: ["/assets/thop2.png"],
      isFeatured: true,
      views: 124,
      likes: 50,
      rating: 4.8,
      reviews: 124,
      wishListed: 0,
    },
    {
      productId: `prod-${uuidv4().slice(0, 16)}`,
      name: "Fiery Red Chilli Pickle",
      slug: "fiery-red-chilli-pickle",
      description: "For spice lovers - intense heat with bold flavors",
      category: "pickle",
      type: "veg",
      ingredients: ["red chillies", "mustard oil", "spices", "salt"],
      nutritionalInfo: {
        servingSize: "10g",
        calories: 25,
        fat: "1.5g",
        sodium: "250mg",
        carbs: "2g",
        fiber: "0.3g",
        protein: "0.1g",
      },
      price: 249,
      discount: 0,
      stock: 80,
      inStock: true,
      spiceLevel: 5,
      isVeg: true,
      imageUrl: "/assets/thop2.png",
      images: ["/assets/thop2.png"],
      isFeatured: false,
      views: 89,
      likes: 30,
      rating: 4.6,
      reviews: 89,
      wishListed: 0,
    },
    {
      productId: `prod-${uuidv4().slice(0, 16)}`,
      name: "Mixed Vegetable Pickle",
      slug: "mixed-vegetable-pickle",
      description:
        "A delightful mix of seasonal vegetables in traditional spices",
      category: "pickle",
      type: "veg",
      ingredients: ["carrots", "cauliflower", "mustard oil", "spices"],
      nutritionalInfo: {
        servingSize: "15g",
        calories: 20,
        fat: "1g",
        sodium: "200mg",
        carbs: "3g",
        fiber: "0.8g",
        protein: "0.3g",
      },
      price: 229,
      discount: 13, // (229 - 199) / 229 * 100 ≈ 13%
      stock: 120,
      inStock: true,
      spiceLevel: 2,
      isVeg: true,
      imageUrl: "/assets/thop2.png",
      images: ["/assets/thop2.png"],
      isFeatured: true,
      views: 156,
      likes: 60,
      rating: 4.7,
      reviews: 156,
      wishListed: 0,
    },
    {
      productId: `prod-${uuidv4().slice(0, 16)}`,
      name: "Lemon Pickle",
      slug: "lemon-pickle",
      description: "Tangy and aromatic lemon pickle with mustard oil",
      category: "pickle",
      type: "veg",
      ingredients: ["lemons", "mustard oil", "spices", "salt"],
      nutritionalInfo: {
        servingSize: "10g",
        calories: 15,
        fat: "1g",
        sodium: "180mg",
        carbs: "2g",
        fiber: "0.4g",
        protein: "0.1g",
      },
      price: 179,
      discount: 0,
      stock: 150,
      inStock: true,
      spiceLevel: 2,
      isVeg: true,
      imageUrl: "/assets/thop2.png",
      images: ["/assets/thop2.png"],
      isFeatured: true,
      views: 203,
      likes: 80,
      rating: 4.9,
      reviews: 203,
      wishListed: 0,
    },
    {
      productId: `prod-${uuidv4().slice(0, 16)}`,
      name: "Garlic Pickle",
      slug: "garlic-pickle",
      description: "Rich and flavorful garlic pickle with herbs",
      category: "pickle",
      type: "veg",
      ingredients: ["garlic", "herbs", "mustard oil", "spices"],
      nutritionalInfo: {
        servingSize: "10g",
        calories: 20,
        fat: "1.2g",
        sodium: "220mg",
        carbs: "2.5g",
        fiber: "0.3g",
        protein: "0.2g",
      },
      price: 259,
      discount: 12, // (259 - 229) / 259 * 100 ≈ 12%
      stock: 90,
      inStock: true,
      spiceLevel: 3,
      isVeg: true,
      imageUrl: "/assets/thop2.png",
      images: ["/assets/thop2.png"],
      isFeatured: false,
      views: 67,
      likes: 25,
      rating: 4.5,
      reviews: 67,
      wishListed: 0,
    },
    {
      productId: `prod-${uuidv4().slice(0, 16)}`,
      name: "Green Chilli Pickle",
      slug: "green-chilli-pickle",
      description: "Fresh green chillis in mustard oil and spices",
      category: "pickle",
      type: "veg",
      ingredients: ["green chillies", "mustard oil", "spices", "salt"],
      nutritionalInfo: {
        servingSize: "10g",
        calories: 22,
        fat: "1.3g",
        sodium: "240mg",
        carbs: "2g",
        fiber: "0.3g",
        protein: "0.1g",
      },
      price: 219,
      discount: 0,
      stock: 85,
      inStock: true,
      spiceLevel: 4,
      isVeg: true,
      imageUrl: "/assets/thop2.png",
      images: ["/assets/thop2.png"],
      isFeatured: false,
      views: 92,
      likes: 35,
      rating: 4.4,
      reviews: 92,
      wishListed: 0,
    },
    {
      productId: `prod-${uuidv4().slice(0, 16)}`,
      name: "Amla Pickle",
      slug: "amla-pickle",
      description: "Tangy Indian gooseberry pickle with mild spices",
      category: "pickle",
      type: "veg",
      ingredients: ["amla", "spices", "oil", "salt"],
      nutritionalInfo: {
        servingSize: "15g",
        calories: 18,
        fat: "0.8g",
        sodium: "200mg",
        carbs: "3g",
        fiber: "1g",
        protein: "0.2g",
      },
      price: 189,
      discount: 0,
      stock: 110,
      inStock: true,
      spiceLevel: 2,
      isVeg: true,
      imageUrl: "/assets/thop2.png",
      images: ["/assets/thop2.png"],
      size: "250g",
      isFeatured: false,
      views: 78,
      likes: 28,
      rating: 4.6,
      reviews: 78,
      wishListed: 0,
    },
    {
      productId: `prod-${uuidv4().slice(0, 16)}`,
      name: "Ginger Pickle",
      slug: "ginger-pickle",
      description: "Zesty ginger pickle with lemon and spices",
      category: "pickle",
      type: "veg",
      ingredients: ["ginger", "lemon", "spices", "oil"],
      nutritionalInfo: {
        servingSize: "15g",
        calories: 25,
        fat: "1g",
        sodium: "210mg",
        carbs: "3.5g",
        fiber: "0.5g",
        protein: "0.2g",
      },
      price: 279,
      discount: 14, // (279 - 239) / 279 * 100 ≈ 14%
      stock: 95,
      inStock: true,
      spiceLevel: 3,
      isVeg: true,
      imageUrl: "/assets/thop2.png",
      images: ["/assets/thop2.png"],
      size: "400g",
      isFeatured: true,
      views: 95,
      likes: 40,
      rating: 4.7,
      reviews: 95,
      wishListed: 0,
    },
    {
      productId: `prod-${uuidv4().slice(0, 16)}`,
      name: "Chicken Pickle",
      slug: "chicken-pickle",
      description: "Spicy chicken pickle with traditional Andhra spices",
      category: "pickle",
      type: "non-veg",
      ingredients: ["chicken", "spices", "oil", "salt"],
      nutritionalInfo: {
        servingSize: "20g",
        calories: 50,
        fat: "3g",
        sodium: "400mg",
        carbs: "2g",
        fiber: "0.2g",
        protein: "4g",
      },
      price: 449,
      discount: 11, // (449 - 399) / 449 * 100 ≈ 11%
      stock: 60,
      inStock: true,
      spiceLevel: 4,
      isVeg: false,
      imageUrl: "/assets/thop2.png",
      images: ["/assets/thop2.png"],
      size: "500g",
      isFeatured: true,
      views: 112,
      likes: 45,
      rating: 4.9,
      reviews: 112,
      wishListed: 0,
    },
    {
      productId: `prod-${uuidv4().slice(0, 16)}`,
      name: "Prawn Pickle",
      slug: "prawn-pickle",
      description: "Coastal style prawn pickle with tangy spices",
      category: "pickle",
      type: "non-veg",
      ingredients: ["prawns", "spices", "oil", "salt"],
      nutritionalInfo: {
        servingSize: "20g",
        calories: 45,
        fat: "2.5g",
        sodium: "350mg",
        carbs: "2g",
        fiber: "0.2g",
        protein: "3.5g",
      },
      price: 499,
      discount: 0,
      stock: 50,
      inStock: true,
      spiceLevel: 3,
      isVeg: false,
      imageUrl: "/assets/thop2.png",
      images: ["/assets/thop2.png"],
      size: "300g",
      isFeatured: false,
      views: 88,
      likes: 35,
      rating: 4.8,
      reviews: 88,
      wishListed: 0,
    },
    {
      productId: `prod-${uuidv4().slice(0, 16)}`,
      name: "Mutton Pickle",
      slug: "mutton-pickle",
      description: "Rich mutton pickle with aromatic spices",
      category: "pickle",
      type: "non-veg",
      ingredients: ["mutton", "spices", "oil", "salt"],
      nutritionalInfo: {
        servingSize: "20g",
        calories: 55,
        fat: "3.5g",
        sodium: "400mg",
        carbs: "2g",
        fiber: "0.2g",
        protein: "4.5g",
      },
      price: 499,
      discount: 10, // (499 - 449) / 499 * 100 ≈ 10%
      stock: 50,
      inStock: true,
      spiceLevel: 4,
      isVeg: false,
      imageUrl: "/assets/thop2.png",
      images: ["/assets/thop2.png"],
      size: "500g",
      isFeatured: true,
      views: 76,
      likes: 30,
      rating: 4.7,
      reviews: 76,
      wishListed: 0,
    },
  ];

  await ProductModel.insertMany(products);
  console.log("Products seeded successfully");
  process.exit();
}

seedProducts().catch(console.error);
